// +build !ignore_autogenerated

/*
Copyright 2018 The Pharmer Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by conversion-gen. Do not edit it manually!

package v1alpha1

import (
	unsafe "unsafe"

	discovery "github.com/etcd-manager/etcd-discovery/apis/discovery"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(scheme *runtime.Scheme) error {
	return scheme.AddGeneratedConversionFuncs(
		Convert_v1alpha1_Member_To_discovery_Member,
		Convert_discovery_Member_To_v1alpha1_Member,
		Convert_v1alpha1_MemberRequest_To_discovery_MemberRequest,
		Convert_discovery_MemberRequest_To_v1alpha1_MemberRequest,
		Convert_v1alpha1_MemberResponse_To_discovery_MemberResponse,
		Convert_discovery_MemberResponse_To_v1alpha1_MemberResponse,
		Convert_v1alpha1_PeerInfo_To_discovery_PeerInfo,
		Convert_discovery_PeerInfo_To_v1alpha1_PeerInfo,
		Convert_v1alpha1_Ping_To_discovery_Ping,
		Convert_discovery_Ping_To_v1alpha1_Ping,
		Convert_v1alpha1_PingRequest_To_discovery_PingRequest,
		Convert_discovery_PingRequest_To_v1alpha1_PingRequest,
		Convert_v1alpha1_PingResponse_To_discovery_PingResponse,
		Convert_discovery_PingResponse_To_v1alpha1_PingResponse,
	)
}

func autoConvert_v1alpha1_Member_To_discovery_Member(in *Member, out *discovery.Member, s conversion.Scope) error {
	out.Request = (*discovery.MemberRequest)(unsafe.Pointer(in.Request))
	out.Response = (*discovery.MemberResponse)(unsafe.Pointer(in.Response))
	return nil
}

// Convert_v1alpha1_Member_To_discovery_Member is an autogenerated conversion function.
func Convert_v1alpha1_Member_To_discovery_Member(in *Member, out *discovery.Member, s conversion.Scope) error {
	return autoConvert_v1alpha1_Member_To_discovery_Member(in, out, s)
}

func autoConvert_discovery_Member_To_v1alpha1_Member(in *discovery.Member, out *Member, s conversion.Scope) error {
	out.Request = (*MemberRequest)(unsafe.Pointer(in.Request))
	out.Response = (*MemberResponse)(unsafe.Pointer(in.Response))
	return nil
}

// Convert_discovery_Member_To_v1alpha1_Member is an autogenerated conversion function.
func Convert_discovery_Member_To_v1alpha1_Member(in *discovery.Member, out *Member, s conversion.Scope) error {
	return autoConvert_discovery_Member_To_v1alpha1_Member(in, out, s)
}

func autoConvert_v1alpha1_MemberRequest_To_discovery_MemberRequest(in *MemberRequest, out *discovery.MemberRequest, s conversion.Scope) error {
	out.PeerURL = in.PeerURL
	return nil
}

// Convert_v1alpha1_MemberRequest_To_discovery_MemberRequest is an autogenerated conversion function.
func Convert_v1alpha1_MemberRequest_To_discovery_MemberRequest(in *MemberRequest, out *discovery.MemberRequest, s conversion.Scope) error {
	return autoConvert_v1alpha1_MemberRequest_To_discovery_MemberRequest(in, out, s)
}

func autoConvert_discovery_MemberRequest_To_v1alpha1_MemberRequest(in *discovery.MemberRequest, out *MemberRequest, s conversion.Scope) error {
	out.PeerURL = in.PeerURL
	return nil
}

// Convert_discovery_MemberRequest_To_v1alpha1_MemberRequest is an autogenerated conversion function.
func Convert_discovery_MemberRequest_To_v1alpha1_MemberRequest(in *discovery.MemberRequest, out *MemberRequest, s conversion.Scope) error {
	return autoConvert_discovery_MemberRequest_To_v1alpha1_MemberRequest(in, out, s)
}

func autoConvert_v1alpha1_MemberResponse_To_discovery_MemberResponse(in *MemberResponse, out *discovery.MemberResponse, s conversion.Scope) error {
	out.ClusterName = in.ClusterName
	out.ClusterToken = in.ClusterToken
	out.PeerURLs = *(*[]string)(unsafe.Pointer(&in.PeerURLs))
	out.EtcdVersion = in.EtcdVersion
	return nil
}

// Convert_v1alpha1_MemberResponse_To_discovery_MemberResponse is an autogenerated conversion function.
func Convert_v1alpha1_MemberResponse_To_discovery_MemberResponse(in *MemberResponse, out *discovery.MemberResponse, s conversion.Scope) error {
	return autoConvert_v1alpha1_MemberResponse_To_discovery_MemberResponse(in, out, s)
}

func autoConvert_discovery_MemberResponse_To_v1alpha1_MemberResponse(in *discovery.MemberResponse, out *MemberResponse, s conversion.Scope) error {
	out.ClusterName = in.ClusterName
	out.ClusterToken = in.ClusterToken
	out.PeerURLs = *(*[]string)(unsafe.Pointer(&in.PeerURLs))
	out.EtcdVersion = in.EtcdVersion
	return nil
}

// Convert_discovery_MemberResponse_To_v1alpha1_MemberResponse is an autogenerated conversion function.
func Convert_discovery_MemberResponse_To_v1alpha1_MemberResponse(in *discovery.MemberResponse, out *MemberResponse, s conversion.Scope) error {
	return autoConvert_discovery_MemberResponse_To_v1alpha1_MemberResponse(in, out, s)
}

func autoConvert_v1alpha1_PeerInfo_To_discovery_PeerInfo(in *PeerInfo, out *discovery.PeerInfo, s conversion.Scope) error {
	out.ID = in.ID
	out.Hosts = *(*[]string)(unsafe.Pointer(&in.Hosts))
	return nil
}

// Convert_v1alpha1_PeerInfo_To_discovery_PeerInfo is an autogenerated conversion function.
func Convert_v1alpha1_PeerInfo_To_discovery_PeerInfo(in *PeerInfo, out *discovery.PeerInfo, s conversion.Scope) error {
	return autoConvert_v1alpha1_PeerInfo_To_discovery_PeerInfo(in, out, s)
}

func autoConvert_discovery_PeerInfo_To_v1alpha1_PeerInfo(in *discovery.PeerInfo, out *PeerInfo, s conversion.Scope) error {
	out.ID = in.ID
	out.Hosts = *(*[]string)(unsafe.Pointer(&in.Hosts))
	return nil
}

// Convert_discovery_PeerInfo_To_v1alpha1_PeerInfo is an autogenerated conversion function.
func Convert_discovery_PeerInfo_To_v1alpha1_PeerInfo(in *discovery.PeerInfo, out *PeerInfo, s conversion.Scope) error {
	return autoConvert_discovery_PeerInfo_To_v1alpha1_PeerInfo(in, out, s)
}

func autoConvert_v1alpha1_Ping_To_discovery_Ping(in *Ping, out *discovery.Ping, s conversion.Scope) error {
	out.Request = (*discovery.PingRequest)(unsafe.Pointer(in.Request))
	out.Response = (*discovery.PingResponse)(unsafe.Pointer(in.Response))
	return nil
}

// Convert_v1alpha1_Ping_To_discovery_Ping is an autogenerated conversion function.
func Convert_v1alpha1_Ping_To_discovery_Ping(in *Ping, out *discovery.Ping, s conversion.Scope) error {
	return autoConvert_v1alpha1_Ping_To_discovery_Ping(in, out, s)
}

func autoConvert_discovery_Ping_To_v1alpha1_Ping(in *discovery.Ping, out *Ping, s conversion.Scope) error {
	out.Request = (*PingRequest)(unsafe.Pointer(in.Request))
	out.Response = (*PingResponse)(unsafe.Pointer(in.Response))
	return nil
}

// Convert_discovery_Ping_To_v1alpha1_Ping is an autogenerated conversion function.
func Convert_discovery_Ping_To_v1alpha1_Ping(in *discovery.Ping, out *Ping, s conversion.Scope) error {
	return autoConvert_discovery_Ping_To_v1alpha1_Ping(in, out, s)
}

func autoConvert_v1alpha1_PingRequest_To_discovery_PingRequest(in *PingRequest, out *discovery.PingRequest, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_PingRequest_To_discovery_PingRequest is an autogenerated conversion function.
func Convert_v1alpha1_PingRequest_To_discovery_PingRequest(in *PingRequest, out *discovery.PingRequest, s conversion.Scope) error {
	return autoConvert_v1alpha1_PingRequest_To_discovery_PingRequest(in, out, s)
}

func autoConvert_discovery_PingRequest_To_v1alpha1_PingRequest(in *discovery.PingRequest, out *PingRequest, s conversion.Scope) error {
	return nil
}

// Convert_discovery_PingRequest_To_v1alpha1_PingRequest is an autogenerated conversion function.
func Convert_discovery_PingRequest_To_v1alpha1_PingRequest(in *discovery.PingRequest, out *PingRequest, s conversion.Scope) error {
	return autoConvert_discovery_PingRequest_To_v1alpha1_PingRequest(in, out, s)
}

func autoConvert_v1alpha1_PingResponse_To_discovery_PingResponse(in *PingResponse, out *discovery.PingResponse, s conversion.Scope) error {
	out.Info = (*discovery.PeerInfo)(unsafe.Pointer(in.Info))
	return nil
}

// Convert_v1alpha1_PingResponse_To_discovery_PingResponse is an autogenerated conversion function.
func Convert_v1alpha1_PingResponse_To_discovery_PingResponse(in *PingResponse, out *discovery.PingResponse, s conversion.Scope) error {
	return autoConvert_v1alpha1_PingResponse_To_discovery_PingResponse(in, out, s)
}

func autoConvert_discovery_PingResponse_To_v1alpha1_PingResponse(in *discovery.PingResponse, out *PingResponse, s conversion.Scope) error {
	out.Info = (*PeerInfo)(unsafe.Pointer(in.Info))
	return nil
}

// Convert_discovery_PingResponse_To_v1alpha1_PingResponse is an autogenerated conversion function.
func Convert_discovery_PingResponse_To_v1alpha1_PingResponse(in *discovery.PingResponse, out *PingResponse, s conversion.Scope) error {
	return autoConvert_discovery_PingResponse_To_v1alpha1_PingResponse(in, out, s)
}
