// +build !ignore_autogenerated

/*
Copyright 2018 The Pharmer Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by conversion-gen. Do not edit it manually!

package v1alpha1

import (
	unsafe "unsafe"

	discovery "github.com/etcd-manager/etcd-discovery/apis/discovery"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(scheme *runtime.Scheme) error {
	return scheme.AddGeneratedConversionFuncs(
		Convert_v1alpha1_EtcdNode_To_discovery_EtcdNode,
		Convert_discovery_EtcdNode_To_v1alpha1_EtcdNode,
		Convert_v1alpha1_JoinCluster_To_discovery_JoinCluster,
		Convert_discovery_JoinCluster_To_v1alpha1_JoinCluster,
		Convert_v1alpha1_JoinClusterRequest_To_discovery_JoinClusterRequest,
		Convert_discovery_JoinClusterRequest_To_v1alpha1_JoinClusterRequest,
		Convert_v1alpha1_JoinClusterResponse_To_discovery_JoinClusterResponse,
		Convert_discovery_JoinClusterResponse_To_v1alpha1_JoinClusterResponse,
		Convert_v1alpha1_PeerInfo_To_discovery_PeerInfo,
		Convert_discovery_PeerInfo_To_v1alpha1_PeerInfo,
		Convert_v1alpha1_Ping_To_discovery_Ping,
		Convert_discovery_Ping_To_v1alpha1_Ping,
		Convert_v1alpha1_PingRequest_To_discovery_PingRequest,
		Convert_discovery_PingRequest_To_v1alpha1_PingRequest,
		Convert_v1alpha1_PingResponse_To_discovery_PingResponse,
		Convert_discovery_PingResponse_To_v1alpha1_PingResponse,
	)
}

func autoConvert_v1alpha1_EtcdNode_To_discovery_EtcdNode(in *EtcdNode, out *discovery.EtcdNode, s conversion.Scope) error {
	out.Name = in.Name
	out.PeerURLs = *(*[]string)(unsafe.Pointer(&in.PeerURLs))
	out.ClientURLs = *(*[]string)(unsafe.Pointer(&in.ClientURLs))
	out.QuarantinedClientURLs = *(*[]string)(unsafe.Pointer(&in.QuarantinedClientURLs))
	return nil
}

// Convert_v1alpha1_EtcdNode_To_discovery_EtcdNode is an autogenerated conversion function.
func Convert_v1alpha1_EtcdNode_To_discovery_EtcdNode(in *EtcdNode, out *discovery.EtcdNode, s conversion.Scope) error {
	return autoConvert_v1alpha1_EtcdNode_To_discovery_EtcdNode(in, out, s)
}

func autoConvert_discovery_EtcdNode_To_v1alpha1_EtcdNode(in *discovery.EtcdNode, out *EtcdNode, s conversion.Scope) error {
	out.Name = in.Name
	out.PeerURLs = *(*[]string)(unsafe.Pointer(&in.PeerURLs))
	out.ClientURLs = *(*[]string)(unsafe.Pointer(&in.ClientURLs))
	out.QuarantinedClientURLs = *(*[]string)(unsafe.Pointer(&in.QuarantinedClientURLs))
	return nil
}

// Convert_discovery_EtcdNode_To_v1alpha1_EtcdNode is an autogenerated conversion function.
func Convert_discovery_EtcdNode_To_v1alpha1_EtcdNode(in *discovery.EtcdNode, out *EtcdNode, s conversion.Scope) error {
	return autoConvert_discovery_EtcdNode_To_v1alpha1_EtcdNode(in, out, s)
}

func autoConvert_v1alpha1_JoinCluster_To_discovery_JoinCluster(in *JoinCluster, out *discovery.JoinCluster, s conversion.Scope) error {
	out.Request = (*discovery.JoinClusterRequest)(unsafe.Pointer(in.Request))
	out.Response = (*discovery.JoinClusterResponse)(unsafe.Pointer(in.Response))
	return nil
}

// Convert_v1alpha1_JoinCluster_To_discovery_JoinCluster is an autogenerated conversion function.
func Convert_v1alpha1_JoinCluster_To_discovery_JoinCluster(in *JoinCluster, out *discovery.JoinCluster, s conversion.Scope) error {
	return autoConvert_v1alpha1_JoinCluster_To_discovery_JoinCluster(in, out, s)
}

func autoConvert_discovery_JoinCluster_To_v1alpha1_JoinCluster(in *discovery.JoinCluster, out *JoinCluster, s conversion.Scope) error {
	out.Request = (*JoinClusterRequest)(unsafe.Pointer(in.Request))
	out.Response = (*JoinClusterResponse)(unsafe.Pointer(in.Response))
	return nil
}

// Convert_discovery_JoinCluster_To_v1alpha1_JoinCluster is an autogenerated conversion function.
func Convert_discovery_JoinCluster_To_v1alpha1_JoinCluster(in *discovery.JoinCluster, out *JoinCluster, s conversion.Scope) error {
	return autoConvert_discovery_JoinCluster_To_v1alpha1_JoinCluster(in, out, s)
}

func autoConvert_v1alpha1_JoinClusterRequest_To_discovery_JoinClusterRequest(in *JoinClusterRequest, out *discovery.JoinClusterRequest, s conversion.Scope) error {
	out.LeadershipToken = in.LeadershipToken
	out.ClusterName = in.ClusterName
	out.ClusterToken = in.ClusterToken
	out.Nodes = *(*[]*discovery.EtcdNode)(unsafe.Pointer(&in.Nodes))
	out.AddNode = (*discovery.EtcdNode)(unsafe.Pointer(in.AddNode))
	out.EtcdVersion = in.EtcdVersion
	return nil
}

// Convert_v1alpha1_JoinClusterRequest_To_discovery_JoinClusterRequest is an autogenerated conversion function.
func Convert_v1alpha1_JoinClusterRequest_To_discovery_JoinClusterRequest(in *JoinClusterRequest, out *discovery.JoinClusterRequest, s conversion.Scope) error {
	return autoConvert_v1alpha1_JoinClusterRequest_To_discovery_JoinClusterRequest(in, out, s)
}

func autoConvert_discovery_JoinClusterRequest_To_v1alpha1_JoinClusterRequest(in *discovery.JoinClusterRequest, out *JoinClusterRequest, s conversion.Scope) error {
	out.LeadershipToken = in.LeadershipToken
	out.ClusterName = in.ClusterName
	out.ClusterToken = in.ClusterToken
	out.Nodes = *(*[]*EtcdNode)(unsafe.Pointer(&in.Nodes))
	out.AddNode = (*EtcdNode)(unsafe.Pointer(in.AddNode))
	out.EtcdVersion = in.EtcdVersion
	return nil
}

// Convert_discovery_JoinClusterRequest_To_v1alpha1_JoinClusterRequest is an autogenerated conversion function.
func Convert_discovery_JoinClusterRequest_To_v1alpha1_JoinClusterRequest(in *discovery.JoinClusterRequest, out *JoinClusterRequest, s conversion.Scope) error {
	return autoConvert_discovery_JoinClusterRequest_To_v1alpha1_JoinClusterRequest(in, out, s)
}

func autoConvert_v1alpha1_JoinClusterResponse_To_discovery_JoinClusterResponse(in *JoinClusterResponse, out *discovery.JoinClusterResponse, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_JoinClusterResponse_To_discovery_JoinClusterResponse is an autogenerated conversion function.
func Convert_v1alpha1_JoinClusterResponse_To_discovery_JoinClusterResponse(in *JoinClusterResponse, out *discovery.JoinClusterResponse, s conversion.Scope) error {
	return autoConvert_v1alpha1_JoinClusterResponse_To_discovery_JoinClusterResponse(in, out, s)
}

func autoConvert_discovery_JoinClusterResponse_To_v1alpha1_JoinClusterResponse(in *discovery.JoinClusterResponse, out *JoinClusterResponse, s conversion.Scope) error {
	return nil
}

// Convert_discovery_JoinClusterResponse_To_v1alpha1_JoinClusterResponse is an autogenerated conversion function.
func Convert_discovery_JoinClusterResponse_To_v1alpha1_JoinClusterResponse(in *discovery.JoinClusterResponse, out *JoinClusterResponse, s conversion.Scope) error {
	return autoConvert_discovery_JoinClusterResponse_To_v1alpha1_JoinClusterResponse(in, out, s)
}

func autoConvert_v1alpha1_PeerInfo_To_discovery_PeerInfo(in *PeerInfo, out *discovery.PeerInfo, s conversion.Scope) error {
	out.ID = in.ID
	out.Addresses = *(*[]string)(unsafe.Pointer(&in.Addresses))
	return nil
}

// Convert_v1alpha1_PeerInfo_To_discovery_PeerInfo is an autogenerated conversion function.
func Convert_v1alpha1_PeerInfo_To_discovery_PeerInfo(in *PeerInfo, out *discovery.PeerInfo, s conversion.Scope) error {
	return autoConvert_v1alpha1_PeerInfo_To_discovery_PeerInfo(in, out, s)
}

func autoConvert_discovery_PeerInfo_To_v1alpha1_PeerInfo(in *discovery.PeerInfo, out *PeerInfo, s conversion.Scope) error {
	out.ID = in.ID
	out.Addresses = *(*[]string)(unsafe.Pointer(&in.Addresses))
	return nil
}

// Convert_discovery_PeerInfo_To_v1alpha1_PeerInfo is an autogenerated conversion function.
func Convert_discovery_PeerInfo_To_v1alpha1_PeerInfo(in *discovery.PeerInfo, out *PeerInfo, s conversion.Scope) error {
	return autoConvert_discovery_PeerInfo_To_v1alpha1_PeerInfo(in, out, s)
}

func autoConvert_v1alpha1_Ping_To_discovery_Ping(in *Ping, out *discovery.Ping, s conversion.Scope) error {
	out.Request = (*discovery.PingRequest)(unsafe.Pointer(in.Request))
	out.Response = (*discovery.PingResponse)(unsafe.Pointer(in.Response))
	return nil
}

// Convert_v1alpha1_Ping_To_discovery_Ping is an autogenerated conversion function.
func Convert_v1alpha1_Ping_To_discovery_Ping(in *Ping, out *discovery.Ping, s conversion.Scope) error {
	return autoConvert_v1alpha1_Ping_To_discovery_Ping(in, out, s)
}

func autoConvert_discovery_Ping_To_v1alpha1_Ping(in *discovery.Ping, out *Ping, s conversion.Scope) error {
	out.Request = (*PingRequest)(unsafe.Pointer(in.Request))
	out.Response = (*PingResponse)(unsafe.Pointer(in.Response))
	return nil
}

// Convert_discovery_Ping_To_v1alpha1_Ping is an autogenerated conversion function.
func Convert_discovery_Ping_To_v1alpha1_Ping(in *discovery.Ping, out *Ping, s conversion.Scope) error {
	return autoConvert_discovery_Ping_To_v1alpha1_Ping(in, out, s)
}

func autoConvert_v1alpha1_PingRequest_To_discovery_PingRequest(in *PingRequest, out *discovery.PingRequest, s conversion.Scope) error {
	out.Info = (*discovery.PeerInfo)(unsafe.Pointer(in.Info))
	return nil
}

// Convert_v1alpha1_PingRequest_To_discovery_PingRequest is an autogenerated conversion function.
func Convert_v1alpha1_PingRequest_To_discovery_PingRequest(in *PingRequest, out *discovery.PingRequest, s conversion.Scope) error {
	return autoConvert_v1alpha1_PingRequest_To_discovery_PingRequest(in, out, s)
}

func autoConvert_discovery_PingRequest_To_v1alpha1_PingRequest(in *discovery.PingRequest, out *PingRequest, s conversion.Scope) error {
	out.Info = (*PeerInfo)(unsafe.Pointer(in.Info))
	return nil
}

// Convert_discovery_PingRequest_To_v1alpha1_PingRequest is an autogenerated conversion function.
func Convert_discovery_PingRequest_To_v1alpha1_PingRequest(in *discovery.PingRequest, out *PingRequest, s conversion.Scope) error {
	return autoConvert_discovery_PingRequest_To_v1alpha1_PingRequest(in, out, s)
}

func autoConvert_v1alpha1_PingResponse_To_discovery_PingResponse(in *PingResponse, out *discovery.PingResponse, s conversion.Scope) error {
	out.Info = (*discovery.PeerInfo)(unsafe.Pointer(in.Info))
	return nil
}

// Convert_v1alpha1_PingResponse_To_discovery_PingResponse is an autogenerated conversion function.
func Convert_v1alpha1_PingResponse_To_discovery_PingResponse(in *PingResponse, out *discovery.PingResponse, s conversion.Scope) error {
	return autoConvert_v1alpha1_PingResponse_To_discovery_PingResponse(in, out, s)
}

func autoConvert_discovery_PingResponse_To_v1alpha1_PingResponse(in *discovery.PingResponse, out *PingResponse, s conversion.Scope) error {
	out.Info = (*PeerInfo)(unsafe.Pointer(in.Info))
	return nil
}

// Convert_discovery_PingResponse_To_v1alpha1_PingResponse is an autogenerated conversion function.
func Convert_discovery_PingResponse_To_v1alpha1_PingResponse(in *discovery.PingResponse, out *PingResponse, s conversion.Scope) error {
	return autoConvert_discovery_PingResponse_To_v1alpha1_PingResponse(in, out, s)
}
